### PR TITLE
EZ-508: code updated for pattern components

### PR DESCRIPTION
**Pull request by kb-indrajith**
added the fonts for pattern components

### CODE REVIEW

**Comment by kuldev** [comment]
Looks good @kb-indrajith @vaibhavjain-in

**Review by vaibhavjain-in — CHANGES_REQUESTED** [review]
Move images to code.

**Comment by kuldev** [comment]
@kb-indrajith 

Please check following.

1. CSS lines are being repeated

font-size: 20px;
  line-height: 24px;
  font-family: 'ProximaNovaT-Thin', sans-serif;
  color: black; 

2. Can we just create a simple class instead these multiple classes.

.map-component .field--name-field-title, .paragraph--type--referenced-card .block-field-blocknodearticletitle a, .paragraph--type--gallery .field--name-field-title {
    .map-component .field--name-field-title, .paragraph--type--referenced-card .block-field-blocknodearticletitle a, .gallery-component .field--name-field-title {

**Review by vaibhavjain-in — CHANGES_REQUESTED** [review]
@kb-indrajith couple things.
1. Remove commented code
2. The file names contain numbers like `_0.jpg`. Can you make sure the file name is clean.

**Comment by kuldev** [comment]
@kb-indrajith any updates here.

**Review by vaibhavjain-in — APPROVED** [review]
LGTM

**Pull request merged**
